services:
  prettytop:
    build: .
    container_name: ${CONTAINER_NAME}
    ports:
      - "${EXPOSED_PORT:-1031}:${MONITOR_PORT:-8765}"
    env_file:
      - .env
    environment:
      - MONITOR_USERNAME=${MONITOR_USERNAME:-admin}
      - MONITOR_PASSWORD=${MONITOR_PASSWORD:-admin}
      - MONITOR_PORT=${MONITOR_PORT:-8765}
      - HOST_PROC=${HOST_PROC}
      - HOST_SYS=${HOST_SYS}
    volumes:
      - /proc:${HOST_PROC}:ro
      - /sys:${HOST_SYS}:ro
      - /var/log:/var/log:ro
      - /var/run/utmp:/var/run/utmp:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./cert:/app/cert:ro
    pid: "host"
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    restart: unless-stopped